export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_CREATE_CLAIMER_REQUEST = 'PRODUCT_CREATE_CLAIMER_REQUEST'
export const PRODUCT_CREATE_CLAIMER_SUCCESS = 'PRODUCT_CREATE_CLAIMER_SUCCESS'
export const PRODUCT_CREATE_CLAIMER_FAIL = 'PRODUCT_CREATE_CLAIMER_FAIL'
export const PRODUCT_CREATE_CLAIMER_RESET = 'PRODUCT_CREATE_CLAIMER_RESET'